"""
services/rca_generator.py - Root Cause Analysis (RCA) document generator.

Generates structured RCA / incident reports in Markdown format and
optionally commits them to a Git repository for tracking.
"""

from __future__ import annotations

import datetime
import os
import re
import textwrap
from pathlib import Path
from typing import Any

from config import get_settings


class RCAGenerator:
    """
    Generate Markdown RCA documents and store them on disk.

    File naming convention:
        docs/incidents/YYYY-MM-DD_<slug>.md
    """

    def __init__(self) -> None:
        self._settings = get_settings()
        self._output_dir = Path(self._settings.docs_output_dir)
        self._output_dir.mkdir(parents=True, exist_ok=True)

    async def generate(
        self,
        issue: str,
        diagnosis: str,
        plan_summary: str,
        exec_results: dict[str, Any] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        """
        Generate an RCA document and save it to disk.

        Parameters
        ----------
        issue:
            Original user-reported issue description.
        diagnosis:
            LLM-generated diagnosis / root cause analysis (Markdown).
        plan_summary:
            Execution plan summary (Markdown).
        exec_results:
            Step results from the Executor (optional).
        metadata:
            Additional key/value metadata to include.

        Returns
        -------
        Absolute path to the generated Markdown file.
        """
        now = datetime.datetime.now(datetime.UTC)
        slug = _slugify(issue)
        filename = f"{now.strftime('%Y-%m-%d')}_{slug}.md"
        filepath = self._output_dir / filename

        content = self._render(
            issue=issue,
            diagnosis=diagnosis,
            plan_summary=plan_summary,
            exec_results=exec_results or {},
            metadata=metadata or {},
            timestamp=now,
        )

        filepath.write_text(content, encoding="utf-8")
        return str(filepath)

    def generate_runbook(self, task: str, steps: list[str]) -> str:
        """
        Generate a simple runbook Markdown document.

        Returns the file path.
        """
        now = datetime.datetime.now(datetime.UTC)
        slug = _slugify(task)
        filename = f"runbook_{now.strftime('%Y-%m-%d')}_{slug}.md"
        filepath = self._output_dir / filename

        lines = [
            f"# Runbook: {task}",
            f"\n**Generated:** {now.strftime('%Y-%m-%d %H:%M:%S')} UTC\n",
            "## Steps\n",
        ]
        for i, step in enumerate(steps, start=1):
            lines.append(f"{i}. {step}")
        lines.append("\n---\n*Auto-generated by AI DevOps Agent*\n")

        filepath.write_text("\n".join(lines), encoding="utf-8")
        return str(filepath)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _render(
        issue: str,
        diagnosis: str,
        plan_summary: str,
        exec_results: dict[str, Any],
        metadata: dict[str, Any],
        timestamp: datetime.datetime,
    ) -> str:
        exec_section = ""
        if exec_results:
            exec_section = "\n## Execution Results\n\n"
            for step, result in exec_results.items():
                exec_section += f"### {step}\n\n```\n{result}\n```\n\n"

        meta_section = ""
        if metadata:
            meta_section = "\n## Metadata\n\n"
            for k, v in metadata.items():
                meta_section += f"- **{k}:** {v}\n"

        return textwrap.dedent(f"""\
            # Incident RCA Report

            **Date:** {timestamp.strftime("%Y-%m-%d %H:%M:%S")} UTC
            **Issue:** {issue}

            ---

            ## Summary

            {diagnosis}

            ---

            ## Execution Plan

            {plan_summary}
            {exec_section}{meta_section}
            ---

            *Auto-generated by AI DevOps Agent*
        """)


def _slugify(text: str, max_len: int = 40) -> str:
    """Convert *text* to a filesystem-safe slug."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.lower())
    slug = slug.strip("_")
    return slug[:max_len]
